### ISSUE TITLE
Spectre.Console is trying to parse output from console app

### ISSUE THREAD

**Issue by sfiruch** [xoofx/ultra#18]
When using `--mode=live`, the standard output from the profiled application is inserted into a Spectre.Console table. Depending on the output of the application, this may lead to a crash (e.g. when the application outputs `[`):

```
Unhandled exception. System.InvalidOperationException: Encountered malformed markup tag at position 27.
   at Spectre.Console.MarkupTokenizer.ReadMarkup() in /_/src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs:line 192
   at Spectre.Console.MarkupTokenizer.MoveNext() in /_/src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs:line 27
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 19
   at Spectre.Console.Markup..ctor(String text, Style style) in /_/src/Spectre.Console/Widgets/Markup.cs:line 42
   at Ultra.Program.StatusTable.<>c.<UpdateTable>b__11_0(String x) in D:\a\ultra\ultra\src\Ultra\Program.cs:line 460
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Spectre.Console.Rows..ctor(IEnumerable`1 children) in /_/src/Spectre.Console/Widgets/Rows.cs:line 28
   at Ultra.Program.StatusTable.UpdateTable() in D:\a\ultra\ultra\src\Ultra\Program.cs:line 460
   at Ultra.Program.<>c__DisplayClass0_4.<Main>b__28(String text) in D:\a\ultra\ultra\src\Ultra\Program.cs:line 270
   at Ultra.Core.EtwUltraProfiler.<>c__DisplayClass15_0.<StartProcess>b__0(Object sender, DataReceivedEventArgs args) in D:\a\ultra\ultra\src\Ultra.Core\EtwUltraProfiler.cs:line 552
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

`--mode=raw` works great as workaround.

(And, once again: Ultra is amazing! Thank you so much!!!)

**Comment by xoofx** [comment]
Forgot likely some `Markup.Escape` again, hopefully fixed via 439b76d and available soon in `2.0.2+`
