### ISSUE TITLE
"Unexpected error" during profiling. 

### ISSUE THREAD

**Issue by educatedpork** [xoofx/ultra#4]
Hi,

Just tried ultra with an app that I'm working on and it failed with a message to console saying

"Unexpected error:An item with the same key has already been added. Key: 4140"

I have both an .etl (920MB) and .etlx (512MB) file in the directory where I launched alpha, but don't know whether it had failed during the etl merge or during the json.gz generation. Unfortunately I can't provide the ETL trace data (private.. work would kill me etc etc), but if there's anything I can do to help identify the root cause then do let me know.

Cheers,
Dean

**Comment by sandyarmstrong** [comment]
Hitting the same thing. No idea if this is supposed to work on .NET FW but I was trying to profile Visual Studio itself.

**Comment by xoofx** [comment]
> "Unexpected error:An item with the same key has already been added. Key: 4140"
> I have both an .etl (920MB) and .etlx (512MB) file in the directory where I launched alpha, but don't know whether it had failed during the etl merge or during the json.gz generation. Unfortunately I can't provide the ETL trace data (private.. work would kill me etc etc), but if there's anything I can do to help identify the root cause then do let me know.

That's ok. If it crashes with that, it is likely during the conversion, so you should have still the ETL files on the disk. You can try to convert the file with some more verbosity and it should hopefully give a more detailled call stack:

```console
ultra --verbose convert --pid xyz your_etl_file.etl
```

The only annoyance here (that I need to improve) is that you need to open the ETL file originally with a [Perfview](https://github.com/microsoft/perfview/releases/) in order to extract the PID of the process that you were trying to profile.

Or you can run the profile again with --verbose as well. It should work. 🤞 

It's an early 1.0.0, so it is likely that there are few bugs like that still around 😅

**Comment by xoofx** [comment]
> Hitting the same thing. No idea if this is supposed to work on .NET FW but I was trying to profile Visual Studio itself.

I haven't tested it with .NET Framework, so dunno if it is working. I only tested it with a few simple .NET (Core) applications.

**Comment by educatedpork** [comment]
Hi @xoofx,

Extracting the PID and running convert with --verbose gives the following callstack at the point of failure:

```
Unexpected error: An item with the same key has already been added. Key: 4140
System.ArgumentException: An item with the same key has already been added. Key: 4140
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Ultra.Core.EtwConverterToFirefox.Convert(String traceFilePath, List`1 processIds, EtwUltraProfilerOptions options) in
D:\a\ultra\ultra\src\Ultra.Core\EtwConverterToFirefox.cs:line 234
   at Ultra.Core.EtwUltraProfiler.Convert(String etlFile, List`1 pIds, EtwUltraProfilerOptions ultraProfilerOptions) in
D:\a\ultra\ultra\src\Ultra.Core\EtwUltraProfiler.cs:line 338
   at Ultra.Program.<>c__DisplayClass0_3.<<Main>b__16>d.MoveNext() in D:\a\ultra\ultra\src\Ultra\Program.cs:line 213
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass32_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 138
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 121
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in /_/src/Spectre.Console/Live/Status/Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in /_/src/Spectre.Console/Live/Status/Status.cs:line 77
   at Ultra.Program.<>c__DisplayClass0_0.<<Main>b__15>d.MoveNext() in D:\a\ultra\ultra\src\Ultra\Program.cs:line 169
--- End of stack trace from previous location ---
   at XenoAtom.CommandLine.Command.RunAsync(IEnumerable`1 arguments, CommandRunConfig runConfig)
   at XenoAtom.CommandLine.Command.RunAsync(IEnumerable`1 arguments, CommandRunConfig runConfig)
   at Ultra.Program.Main(String[] args) in D:\a\ultra\ultra\src\Ultra\Program.cs:line 244
```
In my case, our application is a mix of .NET 8 C#, C++/CLR, and Native.

Hope this helps!
Dean

**Comment by xoofx** [comment]
Hopefully 0c4f181 should fixed it, you can grab 1.0.1 in ~ 10 minutes, let's see 🤞

**Comment by educatedpork** [comment]
Hi @xoofx ,

Release v1.0.1 fixes it, and I now have a .json.gz that I can load into Firefox. 🎉

Thanks for the (_very_) quick fix!

Dean

**Comment by xoofx** [comment]
Cool. I just tried it with VisualStudio devenv.exe and it seems to work ok https://share.firefox.dev/4hT3RLk

**Comment by sandyarmstrong** [comment]
I was able to get a json.gz, but profiler.firefox.com complains about it "Error: Unserializing the profile failed: SyntaxError: Unexpected end of JSON input". Opening the JSON locally it seems fine visually, appears to terminate, etc.

Regardless, thanks for the rapid fix. I'll have to give it another try later. :-)

**Comment by sandyarmstrong** [comment]
@xoofx I tried again, this time attaching to a running process, and it worked! Some tracks like the memory track were missing, which made the profile a lot smaller. Perhaps that made the difference?
